### ISSUE TITLE
DeprecationWarning about use of pkg_resources

### ISSUE THREAD

**Issue by apirogov** [jimporter/mike#166] opened 2023-08-21 09:11 UTC
When using `mike` as a mkdocs plugin, I get the following warning. Would be great if it would be resolved:

```
INFO    -  DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
             File "/home/a.pirogov/.cache/pypoetry/virtualenvs/metador-core-AXME58BY-py3.9/lib/python3.9/site-packages/mike/mkdocs_plugin.py",
           line 6, in <module>
               from pkg_resources import iter_entry_points
             File
           "/home/a.pirogov/.cache/pypoetry/virtualenvs/metador-core-AXME58BY-py3.9/lib/python3.9/site-packages/pkg_resources/__init__.py",
           line 118, in <module>
               warnings.warn(

```

**Comment by jimporter** [comment] 2023-08-21 16:25
Dupe of #148.

**Closed by jimporter** 2023-08-21 16:25 UTC
