### ISSUE TITLE
Social cards for the base URL are redirect images.

### ISSUE THREAD

**Issue by justinxzhao** [jimporter/mike#149] opened 2023-04-03 14:47 UTC
# Summary

Social media cards for http://ludwig.ai/latest is [working as intended](https://www.opengraph.xyz/url/http%3A%2F%2Fludwig.ai%2Flatest).

However, when sharing http://ludwig.ai on social media, the [social card](https://www.opengraph.xyz/url/http%3A%2F%2Fludwig.ai) is a "redirect" box.

This is our publish command:

```
mike deploy --push --update-aliases ${{ env.ludwig_version }} latest  --no-redirect --title="${{ env.ludwig_version }} (latest)"
```

Is there a way to configure `mike` to continue to make `/latest` be the canonical URL while preserving social media cards (or at least not rendering a "redirecting" card) for when `http://ludwig.ai` is shared?

# Configuration and Logs

* Repository: https://github.com/ludwig-ai/ludwig-docs/blob/master/.github/workflows/publish-docs.yml#L42
* `mike` version: 1.1.2

Thanks in advance for any guidance you might have on this!

**Comment by jimporter** [comment] 2023-04-03 16:04
Thanks for the report. This is happening because the main index page is a redirect.

This is a duplicate of #106, though I'm not sure it's actually possible to do what that issue says.

**Closed by jimporter** 2023-04-03 16:04 UTC

**Comment by jimporter** [comment] 2023-04-03 19:54
That said, the main `index.html` page is just a regular HTML file, and so long as it does the right thing regarding redirects, you can use any HTML file you like. It shouldn't be too hard to edit `index.html` in your `gh-pages` branch to include the necessary metadata and then just push that upstream.

**Comment by justinxzhao** [comment] 2023-04-05 16:07
@jimporter thanks for the reply!

We'll give editing index.html in our gh-pages branch to include the necessary metadata a try and report back. Appreciate the advice.
