### ISSUE TITLE
mike 1.1.2 with python 3.11 deprecation warning

### ISSUE THREAD

**Issue by andboss** [jimporter/mike#164] opened 2023-07-12 07:18 UTC
mike 1.1.2 with python 3.11 deprecation warning:

```
INFO     -  DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  File "/usr/local/lib/python3.11/site-packages/mike/mkdocs_plugin.py", line 6, in <module>
    from pkg_resources import iter_entry_points
  File "/usr/local/lib/python3.11/site-packages/pkg_resources/__init__.py", line 118, in <module>
```

**Comment by jimporter** [comment] 2023-07-12 15:37
Dupe of #148.

**Closed by jimporter** 2023-07-12 15:37 UTC

**Comment by andboss** [comment] 2023-07-12 15:50
Is there a new release planed or how can i use this? Thanks!

**Comment by andboss** [comment] 2023-07-12 15:52
sorry, now found the [milestone](https://github.com/jimporter/mike/milestone/1) 👍

**Comment by jimporter** [comment] 2023-07-12 15:58
The easiest is to just use the latest dev build via `pip install git+https://github.com/jimporter/mike.git` or something similar. At minimum, I need to resolve #106 before releasing v2.0, but the rest of the stuff in the milestone would be very nice to include.
